### ISSUE TITLE
program icon path is set to wrong path

### ISSUE THREAD

**Issue by AMBiuki** [haophancs/simple-graph-tool#1]
Hi, **SimpleGraphTool_resource.rc** at line **3**, sets the icon path to this : `IDI_ICON1	ICON	DISCARDABLE	"C:\\Users\\DarkC343\\Desktop\\simple-graph-tool-master\\icons\\foographer.ico"` while the correct path is `IDI_ICON1	ICON	DISCARDABLE	"C:\\Users\\DarkC343\\Desktop\\simple-graph-tool-master\\icon.ico" `

**Comment by haophancs** [comment]
Hi,
Maybe there're some outdated code about setting icon. You may follow [this article](https://stackoverflow.com/questions/1460361/how-to-set-application-icon-in-a-qt-based-project) to reset the icon resource for Qt App
