### ISSUE TITLE
Project file??

### ISSUE THREAD

**Issue by AlejandroBC1007** [haophancs/simple-graph-tool#3]
Hi, saw your demo video and I was quite impressed with how this program works so I decided to download it so I could give it a test for myself but the .pro file is missing and I can’t run the code without it.
I would deeply appreciate it if you shared with me.
Thank you in advance.

**Comment by haophancs** [comment]
I don’t have .pro file because I don’t use QtCreator anymore. Please follow the instruction and build it with CMake
